// Code generated by protoc-gen-go.
// source: lighthouse.proto
// DO NOT EDIT!

/*
Package lighthouse is a generated protocol buffer package.

It is generated from these files:
	lighthouse.proto

It has these top-level messages:
	Location
	User
	Beacon
	Content
	Message
*/
package lighthouse

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// To be transformed to GeoJson - ex)  {"location" : [-71.34, 41.12]}
// See http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-geo-point-type.html
type Location struct {
	Lon              *float64 `protobuf:"fixed64,1,req,name=lon" json:"lon,omitempty"`
	Lat              *float64 `protobuf:"fixed64,2,req,name=lat" json:"lat,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}

func (m *Location) GetLon() float64 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

func (m *Location) GetLat() float64 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

type User struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}

func (m *User) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type Beacon struct {
	Uuid             []byte    `protobuf:"bytes,1,req,name=uuid" json:"uuid,omitempty"`
	Major            *int32    `protobuf:"varint,2,opt,name=major" json:"major,omitempty"`
	Minor            *int32    `protobuf:"varint,3,opt,name=minor" json:"minor,omitempty"`
	Location         *Location `protobuf:"bytes,4,req,name=location" json:"location,omitempty"`
	Owner            *User     `protobuf:"bytes,5,req,name=owner" json:"owner,omitempty"`
	Permissions      []byte    `protobuf:"bytes,6,req,name=permissions" json:"permissions,omitempty"`
	Label            *string   `protobuf:"bytes,7,req,name=label" json:"label,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Beacon) Reset()         { *m = Beacon{} }
func (m *Beacon) String() string { return proto.CompactTextString(m) }
func (*Beacon) ProtoMessage()    {}

func (m *Beacon) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *Beacon) GetMajor() int32 {
	if m != nil && m.Major != nil {
		return *m.Major
	}
	return 0
}

func (m *Beacon) GetMinor() int32 {
	if m != nil && m.Minor != nil {
		return *m.Minor
	}
	return 0
}

func (m *Beacon) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Beacon) GetOwner() *User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Beacon) GetPermissions() []byte {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *Beacon) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

type Content struct {
	Mime             *string `protobuf:"bytes,1,req,name=mime" json:"mime,omitempty"`
	Data             []byte  `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}

func (m *Content) GetMime() string {
	if m != nil && m.Mime != nil {
		return *m.Mime
	}
	return ""
}

func (m *Content) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Message struct {
	Beacon           *Beacon  `protobuf:"bytes,1,req,name=beacon" json:"beacon,omitempty"`
	Timestamp        *float64 `protobuf:"fixed64,2,req,name=timestamp" json:"timestamp,omitempty"`
	From             *User    `protobuf:"bytes,3,req,name=from" json:"from,omitempty"`
	To               []*User  `protobuf:"bytes,4,rep,name=to" json:"to,omitempty"`
	Body             *Content `protobuf:"bytes,5,req,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetBeacon() *Beacon {
	if m != nil {
		return m.Beacon
	}
	return nil
}

func (m *Message) GetTimestamp() float64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Message) GetFrom() *User {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Message) GetTo() []*User {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Message) GetBody() *Content {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
}
