// Code generated by protoc-gen-go.
// source: passport.proto
// DO NOT EDIT!

/*
Package passport is a generated protocol buffer package.

It is generated from these files:
	passport.proto

It has these top-level messages:
	Blob
	Attribute
	Login
	Application
	Account
*/
package passport

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Attribute_Type int32

const (
	Attribute_STRING Attribute_Type = 1
	Attribute_NUMBER Attribute_Type = 2
	Attribute_BOOL   Attribute_Type = 3
	Attribute_BLOB   Attribute_Type = 4
)

var Attribute_Type_name = map[int32]string{
	1: "STRING",
	2: "NUMBER",
	3: "BOOL",
	4: "BLOB",
}
var Attribute_Type_value = map[string]int32{
	"STRING": 1,
	"NUMBER": 2,
	"BOOL":   3,
	"BLOB":   4,
}

func (x Attribute_Type) Enum() *Attribute_Type {
	p := new(Attribute_Type)
	*p = x
	return p
}
func (x Attribute_Type) String() string {
	return proto.EnumName(Attribute_Type_name, int32(x))
}
func (x *Attribute_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Attribute_Type_value, data, "Attribute_Type")
	if err != nil {
		return err
	}
	*x = Attribute_Type(value)
	return nil
}

type Login_Status int32

const (
	Login_CREATED  Login_Status = 1
	Login_VERIFIED Login_Status = 2
	Login_BLOCKED  Login_Status = 3
)

var Login_Status_name = map[int32]string{
	1: "CREATED",
	2: "VERIFIED",
	3: "BLOCKED",
}
var Login_Status_value = map[string]int32{
	"CREATED":  1,
	"VERIFIED": 2,
	"BLOCKED":  3,
}

func (x Login_Status) Enum() *Login_Status {
	p := new(Login_Status)
	*p = x
	return p
}
func (x Login_Status) String() string {
	return proto.EnumName(Login_Status_name, int32(x))
}
func (x *Login_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Login_Status_value, data, "Login_Status")
	if err != nil {
		return err
	}
	*x = Login_Status(value)
	return nil
}

type Blob struct {
	Type             *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Data             []byte  `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Blob) Reset()         { *m = Blob{} }
func (m *Blob) String() string { return proto.CompactTextString(m) }
func (*Blob) ProtoMessage()    {}

func (m *Blob) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Blob) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Attribute struct {
	Type             *Attribute_Type `protobuf:"varint,1,req,name=type,enum=passport.Attribute_Type" json:"type,omitempty"`
	Key              *string         `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	StringValue      *string         `protobuf:"bytes,3,opt,name=string_value" json:"string_value,omitempty"`
	NumberValue      *float64        `protobuf:"fixed64,4,opt,name=number_value" json:"number_value,omitempty"`
	BoolValue        *bool           `protobuf:"varint,5,opt,name=bool_value" json:"bool_value,omitempty"`
	BlobValue        *Blob           `protobuf:"bytes,6,opt,name=blob_value" json:"blob_value,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}

func (m *Attribute) GetType() Attribute_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Attribute_STRING
}

func (m *Attribute) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Attribute) GetStringValue() string {
	if m != nil && m.StringValue != nil {
		return *m.StringValue
	}
	return ""
}

func (m *Attribute) GetNumberValue() float64 {
	if m != nil && m.NumberValue != nil {
		return *m.NumberValue
	}
	return 0
}

func (m *Attribute) GetBoolValue() bool {
	if m != nil && m.BoolValue != nil {
		return *m.BoolValue
	}
	return false
}

func (m *Attribute) GetBlobValue() *Blob {
	if m != nil {
		return m.BlobValue
	}
	return nil
}

type Login struct {
	Id               *string       `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Status           *Login_Status `protobuf:"varint,2,opt,name=status,enum=passport.Login_Status,def=1" json:"status,omitempty"`
	Email            *string       `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone            *string       `protobuf:"bytes,4,opt,name=phone" json:"phone,omitempty"`
	Password         *string       `protobuf:"bytes,5,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}

const Default_Login_Status Login_Status = Login_CREATED

func (m *Login) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Login) GetStatus() Login_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Default_Login_Status
}

func (m *Login) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *Login) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *Login) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type Application struct {
	Id               *string      `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Status           *string      `protobuf:"bytes,2,req,name=status" json:"status,omitempty"`
	AccountId        *string      `protobuf:"bytes,3,req,name=accountId" json:"accountId,omitempty"`
	StartTimestamp   *float64     `protobuf:"fixed64,4,req,name=startTimestamp" json:"startTimestamp,omitempty"`
	Attributes       []*Attribute `protobuf:"bytes,5,rep,name=attributes" json:"attributes,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}

func (m *Application) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Application) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *Application) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *Application) GetStartTimestamp() float64 {
	if m != nil && m.StartTimestamp != nil {
		return *m.StartTimestamp
	}
	return 0
}

func (m *Application) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type Account struct {
	Id               *string        `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Status           *string        `protobuf:"bytes,2,req,name=status" json:"status,omitempty"`
	Primary          *Login         `protobuf:"bytes,3,req,name=primary" json:"primary,omitempty"`
	CreatedTimestamp *float64       `protobuf:"fixed64,4,req,name=createdTimestamp" json:"createdTimestamp,omitempty"`
	Services         []*Application `protobuf:"bytes,5,rep,name=services" json:"services,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}

func (m *Account) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Account) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *Account) GetPrimary() *Login {
	if m != nil {
		return m.Primary
	}
	return nil
}

func (m *Account) GetCreatedTimestamp() float64 {
	if m != nil && m.CreatedTimestamp != nil {
		return *m.CreatedTimestamp
	}
	return 0
}

func (m *Account) GetServices() []*Application {
	if m != nil {
		return m.Services
	}
	return nil
}

func init() {
	proto.RegisterEnum("passport.Attribute_Type", Attribute_Type_name, Attribute_Type_value)
	proto.RegisterEnum("passport.Login_Status", Login_Status_name, Login_Status_value)
}
