// Code generated by protoc-gen-go.
// source: passport_client.proto
// DO NOT EDIT!

/*
Package passport is a generated protocol buffer package.

It is generated from these files:
	passport_client.proto
	passport.proto

It has these top-level messages:
	AuthRequest
	AuthResponse
	Login
*/
package passport

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Login_Status int32

const (
	Login_CREATED  Login_Status = 1
	Login_VERIFIED Login_Status = 2
	Login_BLOCKED  Login_Status = 3
)

var Login_Status_name = map[int32]string{
	1: "CREATED",
	2: "VERIFIED",
	3: "BLOCKED",
}
var Login_Status_value = map[string]int32{
	"CREATED":  1,
	"VERIFIED": 2,
	"BLOCKED":  3,
}

func (x Login_Status) Enum() *Login_Status {
	p := new(Login_Status)
	*p = x
	return p
}
func (x Login_Status) String() string {
	return proto.EnumName(Login_Status_name, int32(x))
}
func (x *Login_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Login_Status_value, data, "Login_Status")
	if err != nil {
		return err
	}
	*x = Login_Status(value)
	return nil
}

type AuthRequest struct {
	Password         *string `protobuf:"bytes,1,req,name=password" json:"password,omitempty"`
	Email            *string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Phone            *string `protobuf:"bytes,3,opt,name=phone" json:"phone,omitempty"`
	Application      *string `protobuf:"bytes,4,opt,name=application" json:"application,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}

func (m *AuthRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *AuthRequest) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *AuthRequest) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *AuthRequest) GetApplication() string {
	if m != nil && m.Application != nil {
		return *m.Application
	}
	return ""
}

type AuthResponse struct {
	Token            *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}

func (m *AuthResponse) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type Login struct {
	Id       *string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Status   *Login_Status `protobuf:"varint,2,opt,name=status,enum=passport.Login_Status,def=1" json:"status,omitempty"`
	Email    *string       `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone    *string       `protobuf:"bytes,4,opt,name=phone" json:"phone,omitempty"`
	Password *string       `protobuf:"bytes,5,req,name=password" json:"password,omitempty"`
	// Loccation in GeoJson - ex)  {"location" : [-71.34, 41.12]} -- [lon, lat]
	// See http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-geo-point-type.html
	Location         []float64 `protobuf:"fixed64,6,rep,name=location" json:"location,omitempty"`
	Username         *string   `protobuf:"bytes,7,opt,name=username" json:"username,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}

const Default_Login_Status Login_Status = Login_CREATED

func (m *Login) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Login) GetStatus() Login_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Default_Login_Status
}

func (m *Login) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *Login) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *Login) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *Login) GetLocation() []float64 {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Login) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func init() {
	proto.RegisterEnum("passport.Login_Status", Login_Status_name, Login_Status_value)
}
